config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'showers#index'
  resources :users, only: :show
  resources :showers do
    resources :bookings, only: [ :show, :create, :edit, :update, :destroy ]
  end

  get 'results', to: 'showers#results'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :shower

  validates :date, presence: true
  # validates :time, presence: true

  def self.time
    ['9:00 - 9:30', '9:30 - 10:00', '10:00 - 10:30', '10:30 - 11:00', '13:00 - 13:30', '13:30 - 14:00', '16:00 - 16:30', '16:30 - 17:00', '18:00 - 18:30', '19:30 - 20:00']
  end
end

app/models/shower.rb
class Shower < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  validates :price, numericality: { only_integer: true }
  validates :description, :address, :features, presence: true

  include PgSearch
  pg_search_scope :search_by_name_and_address,
    against: [:title, :address],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :owned_showers, class_name: 'Shower'
  has_many :booked_showers, through: :bookings, source: :shower

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Below code allows us to store the user's location before authenticating to redirect him back to that page
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :first_name, :last_name, :owner])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :first_name, :last_name, :owner])
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    shower = Shower.find(params[:shower_id])

    @booking.user = current_user
    @booking.shower = shower

    if @booking.save
      redirect_to user_path(current_user)
    else
      render "showers/show"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.new(booking_params)
    @booking.update
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time)
  end
end

app/controllers/showers_controller.rb
class ShowersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :results]
  before_action :set_shower, only: [:show, :edit, :update, :destroy]

  def index
    @showers = Shower.all
  end

  def results
    showers = Shower.search_by_name_and_address(params[:query])
    @results = showers.where.not(latitude: nil, longitude: nil)

    @markers = @results.map do |result|
      {
        lat: result.latitude,
        lng: result.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { result: result })
      }
    end
  end

  def new
    @shower = Shower.new
  end

  def create
    @shower = Shower.new(shower_params)
    @shower.user = current_user
    if @shower.save
      current_user.owner = true
      redirect_to shower_path(@shower)
    else
      render :new
    end
  end

  def show
    @shower = Shower.find(params[:id])
    @booking = Booking.new

    @markers = {
      lat: @shower.latitude,
      lng: @shower.longitude,
      infoWindow: render_to_string(partial: "infowindow", locals: { result: @shower })
    }
  end

  def edit
  end

  def update
    if @shower.update(shower_params)
      redirect_to shower_path(@shower)
    else
      render :new
    end
  end

  def destroy
    @shower = Shower.find(params[:id])
    @shower.destroy

    redirect_to showers_path
  end

  private

  def shower_params
    params.require(:shower).permit(:title, :description, :address, :features, :price, :photo)
  end

  def set_shower
    @shower = Shower.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [shower, booking], html: { class: "form-group"} do |f| %>
<%= f.input :date, label: false, class: "form-text text-muted" %>
<%= f.input :time, collection: Booking.time, selected: '9:30 - 10:00', label: false, class: "form-text text-muted" %>
<%= f.submit 'Book Shower', class: "btn btn-primary mt-2 btn-block" %>
<% end %>

app/views/bookings/edit.html.erb
<%= render 'booking_form' %>

app/views/layouts/_alert.html.erb
<div class="flash flash-danger alert alert-dismissible fade show" role="alert">
  <span><strong>Oops!</strong> 😱 <%= alert %></span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright" id="commits">

  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <% if user_signed_in? %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
      </li>
      <% if current_user.owner %>
      <li class="nav-item">
        <%= link_to "List a shower", new_shower_path, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item dropdown">
        <% if current_user.avatar.present? %>
        <%= cl_image_tag current_user.avatar, width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
  <% else %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn-light" %>
      </li>
    </ul>
  </div>
  <% end %>
</div>

app/views/layouts/_notice.html.erb
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 <%= notice %>&nbsp</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Spot a Shower</title>
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
  <script src="<%= ENV['FONTAWESOME_URL'] %>"></script>

</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="main-content">
    <%= yield %>

    <% if notice %>
      <%= render 'layouts/notice' %>
    <% end %>

    <% if alert %>
      <%= render 'layouts/alert' %>
    <% end %>

  </div>
  <%= render 'layouts/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/showers/_form.html.erb
<%= simple_form_for shower do |f| %>

  <%= f.input :title %>
  <%= f.input :description, as: :text %>
  <%= f.input :address %>
  <%= f.input :features %>
  <%= f.input :price %>
  <%= f.input :photo, class: "form-control-file" %>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/showers/_infowindow.html.erb
<div class="card-shower">
  <% if result.photo.present? %>
    <%= cl_image_tag result.photo, crop: :fill%>
  <% else %>
    <%= image_tag('bath.jpg') %>
  <% end %>
    <div class="card-shower-infos">
      <div>
        <h1><%= result.title %></h1>
        <h2><%= result.address %></h2>
      </div>
      <h2 class="card-shower-pricing">€<%= result.price %></h2>
      <%= image_tag "avatar.png", class:"card-shower-user avatar-bordered" %>
    </div>
</div>

app/views/showers/edit.html.erb
<div class="container">
  <h1>Edit <%= @shower.description %></h1>

  <%= render 'form', shower: @shower %>
</div>

app/views/showers/index.html.erb
<div class="banner-index">
  <div class="container">
    <h1>We've Got You Covered <span>[ and </span><span class="typed"></span><span> ]</span></h1>
    <p>Take a shower on the spot! We have the solution to unexpected events!</p>

    <div class="pt-2">
      <%= form_tag results_path, class: "form-group", method: :get do %>
      <div class='row'>
        <div class="input-group-append col-12 col-sm-8 col-lg-6">
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
            placeholder: "Type here..." %>
            <%= submit_tag "Search", class: "btn btn-primary mt-0" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>


  <div class="container pt-3 pb-5">
    <div class="card">
      <% @showers.each do |shower| %>
      <%= link_to shower_path(shower) do %>
      <div class="card-shower">
        <% if shower.photo.present? %>
        <%= cl_image_tag shower.photo, crop: :fill%>
        <% else %>
        <%= image_tag('bath.jpg') %>
        <% end %>
        <div class="card-shower-infos">
          <div>
            <h1><%= shower.title %></h1>
            <h2><%= shower.address.split(',').first(2).join(', ') %></h2>
          </div>
          <h2 class="card-shower-pricing">€<%= shower.price %></h2>
          <% user = User.find(shower.user_id) %>
          <% if user.avatar.present? %>
          <%= cl_image_tag user.avatar, width: 40, height: 40, crop: :thumb, gravity: :face, class:"card-shower-user avatar-bordered"%>
          <% else %>
          <%= image_tag "avatar.png", class:"card-shower-user avatar-bordered" %>
          <% end %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>

app/views/showers/new.html.erb
<div class="container pt-3">
  <h1>Add a new shower</h1>
  <p>Offer your shower and benefit from it!</p>

  <%= render 'form', shower: @shower %>
</div>

app/views/showers/results.html.erb
<div class="row pl-3">
  <div class="col-12 col-sm-7 col-lg-6">
     <div class="card">
      <% @results.each do |shower| %>
      <%= link_to shower_path(shower) do %>
      <div class="card-shower">
        <% if shower.photo.present? %>
        <%= cl_image_tag shower.photo, crop: :fill%>
        <% else %>
        <%= image_tag('bath.jpg') %>
        <% end %>
        <div class="card-shower-infos">
          <div>
            <h1><%= shower.title %></h1>
            <h2><%= shower.address.split(',').first(2).join(', ') %></h2>
          </div>
          <h2 class="card-shower-pricing">€<%= shower.price %></h2>
          <% if shower.user.avatar.present? %>
            <%= cl_image_tag shower.user.avatar, width: 56, height: 56, crop: :thumb, gravity: :face, class:"card-shower-user avatar-bordered" %>
          <% else %>
            <%= image_tag "avatar.png",  class:"card-shower-user avatar-bordered" %>
          <% end %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-12 col-sm-5 col-lg-6">
    <div
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY']%>"
    ></div>
  </div>
</div>

app/views/showers/show.html.erb
<% if @shower.photo.present? %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @shower.photo, crop: :fill %>');">
</div>
<% else %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/dtzq3rssy/image/upload/v1563291134/architecture-bathroom-bathtub-1910472_om1swy.jpg');">
</div>
<% end %>

<div class="container border shadow-sm my-3 py-3 bg-white rounded">

  <div class="d-flex bd-highlight">
    <div class="p-2 flex-grow-1 bd-highlight">
      <div class="d-flex justify-content-between w-50 border-bottom">

        <div>
          <h1 class = "shower-title-color"><%= @shower.title %> </h1>
          <p> <%= @shower.address %> </p>
        </div>

        <div class="bd-highlight w-25 text-center flex-shrink-1 ">
          <% if @shower.user.avatar.present? %>
          <%= cl_image_tag @shower.user.avatar, width: 56, height: 56, crop: :thumb, gravity: :face, class:"avatar-large" %>
          <% else %>
          <%= image_tag "avatar.png",  class:"avatar-large" %>
          <% end %>
          <p><strong><%= @shower.user.first_name %></strong></p>
        </div>
      </div>

      <h3 class="mt-3"> Overview: </h3>
      <ul class="list-unstyled">
        <li class="py-2"><i class="fas fa-shower icon"></i><strong> Description provided by the owner of this shower: </strong></li>
        <li class="pl-2 "> <%= @shower.description %> </li>
        <li class="py-2"><i class="fas fa-spa icon"></i><strong> Features included:</strong></li>
        <li class="pl-2"> <%= @shower.features %> </li>
        <li class="py-2"><i class="fas fa-tag icon"></i><strong> Pricing</strong></li>
        <li class="pl-2"> <%= @shower.price %> <span>€</span> </li>
      </ul>
    </div>

    <div class="p-3 d-flex flex-column justify-content-between">
      <div
        id="map"
        style="height: 250px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY']%>"
      ></div>
      <div>
        <%= render 'bookings/form', shower: @shower, booking: @booking %>
      </div>
    </div>
  </div>
  <hr>
  <div class="d-flex justify-content-center">
    <%= link_to "Edit", edit_shower_path(@shower), class: "btn btn-link m-1" %>
    <%= link_to "Delete Shower", shower_path(@shower), class: "btn btn-danger m-1",
    method: :delete,
    data: { confirm: "Please confirm you want to delete this shower" } %>
  </div>

</div>

app/views/users/_bookings.html.erb
<div class="bookings">
  <div class="card">
    <% current_user.bookings.each do |booking| %>
    <% shower = current_user.booked_showers.where(id: booking.shower_id).last %>
    <div class="card-shower">
     <% if shower.photo.present? %>
     <%= cl_image_tag shower.photo, crop: :fill%>
     <% else %>
     <%= image_tag('bath.jpg') %>
     <% end %>
     <div class="card-shower-infos">
      <div>
        <h1><strong><%= shower.title %></strong></h1>
        <h1><%= booking.date %></h1>
        <p><%= shower.address.split(',').first(2).join(', ') %></p>
        <%= link_to "Cancel", shower_booking_path(shower, booking), method: :delete, class:"btn btn-danger mt-3" %>
      </div>
      <h2 class="card-shower-pricing"><%= " #{shower.price}€ " %></h2>
      <% if current_user.avatar.present? %>
        <%= cl_image_tag current_user.avatar, width: 40, height: 40, crop: :thumb, gravity: :face, class:"card-shower-user avatar-bordered"%>
      <% else %>
        <%= image_tag "avatar.png",  class:"avatar-large" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/users/_offerings.html.erb
<div class="offerings">
  <div class="card">
    <% current_user.owned_showers.each do |shower| %>
    <%= link_to shower_path(shower) do %>
    <div class="card-shower">
     <% if shower.photo.present? %>
     <%= cl_image_tag shower.photo, crop: :fill%>
     <% else %>
     <%= image_tag('bath.jpg') %>
     <% end %>
     <div class="card-shower-infos">
      <div>
        <h1><strong><%= shower.title %></strong></h1>
        <p><%= shower.address.split(',').first(2).join(', ') %></p>
      </div>
      <h2 class="card-shower-pricing"><%= " #{shower.price}€ " %></h2>
       <% if current_user.avatar.present? %>
      <%= cl_image_tag current_user.avatar, width: 40, height: 40, crop: :thumb, gravity: :face, class:"card-shower-user avatar-bordered"%>
      <% else %>
      <%= image_tag "avatar.png",  class:"avatar-large" %>
      <% end %>
    </div>
  </div>
  <% end %>
  <% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Edit your infomration</h1>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
  <div class="row">
    <div class="d-flex justify-content-center col-0 col-sm-6 col-md-4 col-lg-3 p-4">
      <div class = "p-4">
      <% if current_user.avatar.present? %>
      <%= cl_image_tag current_user.avatar, width: 200, height: 200, crop: :thumb, gravity: :face, radius: 8, effect: :sharpen, class: "shadow mt-3" %>
      <% else %>
      <%= image_tag "avatar.png",  class:"avatar-large" %>
      <% end %>

      <div class="">
        <h3 class="pt-4"><%= current_user.first_name %> <%= current_user.last_name %></h3>
        <p class="py-2 text-secondary"><%= current_user.email %></p>
        <%= link_to "Edit", edit_user_registration_path, class: "btn btn-md btn-primary m-1" %>
      </div>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-8 col-lg-9 p-0 ">
      <section id="tabs">
          <div class="row">
            <div class="col-auto">
              <nav class="nad nav-pills nav-fill">
                <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                  <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Listed Showers</a>
                  <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Your bookings</a>

                </div>
              </nav>
              <div class="tab-content px-3 px-sm-0" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                 <div>
                  <% if current_user.owned_showers.present? %>
                  <div class="showers">
                    <%= render 'users/offerings' %>
                  </div>
                  <% end %>

                </div>
              </div>
              <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">

                <div>
                  <% if current_user.bookings.present? %>
                  <div class="showers">
                    <%= render 'users/bookings' %>
                  </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
  </div>
</div>